apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnbhjg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnbhjg
  template:
    metadata:
      labels:
        app: mnbhjg
    spec:
      containers:
      - image: okteto.dev/mnbhjg:latest
        name: mnbhjg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "11ca42a2-1bc1-40b5-a8fc-87fc12048a70"
        - name: Vless_Path
          value: "/vl5987c5"
        - name: Vmess_UUID
          value: "11ca42a2-1bc1-40b5-a8fc-87fc12048a70"
        - name: Vmess_Path
          value: "/vm6fvfh66"
        - name: Share_Path
          value: "/v2link"
